"use client";

import { PageHeader } from "@/components/shared/page-header";
import { StatCard } from "@/components/dashboard/stat-card";
import { TeamPerformanceTable } from "@/components/spv/team-performance-table";
import { UsersRound, DollarSign, Percent } from "lucide-react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { PerformanceChart } from "@/components/dashboard/performance-chart";
import { useCurrentUser } from "@/hooks/use-current-user";
import { useCollection, useFirestore } from "@/firebase";
import { collection, query, where } from "firebase/firestore";
import type { Sale } from "@/lib/mock-data";
import { spvTeams } from "@/lib/mock-data"; // still using mock for team structure
import type { AppUser } from "@/hooks/use-current-user";

export default function SpvDashboard() {
  const { user, loading: userLoading } = useCurrentUser();
  const firestore = useFirestore();

  // Assuming user object has salesCode which is SPV's code
  const spvCode = user?.salesCode;
  
  const teamSalesCodes = spvCode ? spvTeams[spvCode] : [];

  const { data: teamMembers, loading: teamLoading } = useCollection<AppUser>(
    firestore && teamSalesCodes && teamSalesCodes.length > 0
      ? query(collection(firestore, "users"), where("salesCode", "in", teamSalesCodes))
      : null
  );

  const { data: teamSales, loading: salesLoading } = useCollection<Sale>(
    firestore && teamSalesCodes && teamSalesCodes.length > 0
      ? query(collection(firestore, "sales"), where("salesCode", "in", teamSalesCodes))
      : null
  );

  if (userLoading || teamLoading || salesLoading) {
    return <div>Loading...</div>
  }

  const totalSalesAmount = teamSales?.reduce((acc, sale) => acc + sale.amount, 0) || 0;
  
  // Mock conversion rate
  const conversionRate = 35.5;

  return (
    <div className="space-y-8">
      <PageHeader title="Supervisor Dashboard" description="Monitor your team's performance and sales data." />
      
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <StatCard
          title="Team Members"
          value={teamMembers?.length.toString() || '0'}
          icon={UsersRound}
          description="Salespersons under your supervision"
        />
        <StatCard
          title="Team Sales (Month)"
          value={`$${totalSalesAmount.toLocaleString()}`}
          icon={DollarSign}
          description="Total revenue generated by your team this month"
        />
        <StatCard
          title="Conversion Rate"
          value={`${conversionRate}%`}
          icon={Percent}
          description="Lead to sale conversion rate for the team"
        />
      </div>

      <div className="grid grid-cols-1 gap-8 lg:grid-cols-5">
        <Card className="lg:col-span-3">
            <CardHeader>
                <CardTitle>Team Performance</CardTitle>
            </CardHeader>
            <CardContent>
                {spvCode && <TeamPerformanceTable spvCode={spvCode} />}
            </CardContent>
        </Card>
        <Card className="lg:col-span-2">
            <CardHeader>
                <CardTitle>Weekly Sales Trend</CardTitle>
            </CardHeader>
            <CardContent>
                <PerformanceChart sales={teamSales} />
            </CardContent>
        </Card>
      </div>
    </div>
  );
}
