import { PageHeader } from "@/components/shared/page-header";
import { StatCard } from "@/components/dashboard/stat-card";
import { spvTeams, users, sales } from "@/lib/mock-data";
import { TeamPerformanceTable } from "@/components/spv/team-performance-table";
import { UsersRound, DollarSign, Percent } from "lucide-react";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { PerformanceChart } from "@/components/dashboard/performance-chart";

const SPV_CODE = 'SPV01'; // Mock current SPV

export default function SpvDashboard() {
  const teamSalesCodes = spvTeams[SPV_CODE] || [];
  const teamMembers = users.filter(u => teamSalesCodes.includes(u.salesCode));
  const teamSales = sales.filter(s => teamSalesCodes.includes(s.salesCode));
  const totalSalesAmount = teamSales.reduce((acc, sale) => acc + sale.amount, 0);
  
  // Mock conversion rate
  const conversionRate = 35.5;

  return (
    <div className="space-y-8">
      <PageHeader title="Supervisor Dashboard" description="Monitor your team's performance and sales data." />
      
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <StatCard
          title="Team Members"
          value={teamMembers.length.toString()}
          icon={UsersRound}
          description="Salespersons under your supervision"
        />
        <StatCard
          title="Team Sales (Month)"
          value={`$${totalSalesAmount.toLocaleString()}`}
          icon={DollarSign}
          description="Total revenue generated by your team this month"
        />
        <StatCard
          title="Conversion Rate"
          value={`${conversionRate}%`}
          icon={Percent}
          description="Lead to sale conversion rate for the team"
        />
      </div>

      <div className="grid grid-cols-1 gap-8 lg:grid-cols-5">
        <Card className="lg:col-span-3">
            <CardHeader>
                <CardTitle>Team Performance</CardTitle>
            </CardHeader>
            <CardContent>
                <TeamPerformanceTable spvCode={SPV_CODE} />
            </CardContent>
        </Card>
        <Card className="lg:col-span-2">
            <CardHeader>
                <CardTitle>Weekly Sales Trend</CardTitle>
            </CardHeader>
            <CardContent>
                <PerformanceChart />
            </CardContent>
        </Card>
      </div>
    </div>
  );
}
